### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by rushi12565** [azaelgg/Jajaja-Account-Nuker#12]
Traceback (most recent call last):
  File "jajaja.py", line 2, in <module>
    import threading, requests, discord, random, time, os
  File "/home/rushyendra/.local/lib/python3.8/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/home/rushyendra/.local/lib/python3.8/site-packages/discord/client.py", line 33, in <module>
    import aiohttp
  File "/home/rushyendra/.local/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/home/rushyendra/.local/lib/python3.8/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/home/rushyendra/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 13, in <module>
    from . import hdrs, helpers
  File "/home/rushyendra/.local/lib/python3.8/site-packages/aiohttp/helpers.py", line 30
    ensure_future = asyncio.async
                            ^
SyntaxError: invalid syntax

**Comment by azaelgg** [comment]
retry, just revamped code
