### ISSUE TITLE
chrome driver

### ISSUE THREAD

**Issue by ResolutePSD** [azaelgg/Jajaja-Account-Nuker#18]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver.exe': 'chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/icknes/Desktop/python base:test/test3.py", line 185, in <module>
    client.input_loop()
  File "/Users/icknes/Desktop/python base:test/test3.py", line 173, in input_loop
    return self.input_loop()
  File "/Users/icknes/Desktop/python base:test/test3.py", line 172, in input_loop
    self.thread_requests(command=cmd)
  File "/Users/icknes/Desktop/python base:test/test3.py", line 139, in thread_requests
    self.token_login()
  File "/Users/icknes/Desktop/python base:test/test3.py", line 97, in token_login
    driver = webdriver.Chrome(CHROME_DRIVER_PATH, options=opts)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by ResolutePSD** [comment]
wait, mb i didnt see the download for chrome driver
